/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package genericexpertsystem;

import java.util.ArrayList;

/**
 *
 * @author Peeral
 */
public class HumanInterferenceGUI2 extends javax.swing.JFrame {

    static private double humanFactor;
    EnvironmentalInfluenceGUI eig;
    /**
     * Creates new form HumanInterferenceGUI2
     */
    public HumanInterferenceGUI2() {
        initComponents();
    }

    public void setHumanFactor(double humanFactor) {
        HumanInterferenceGUI2.humanFactor = humanFactor;
    }
    
    public double getHumanFactor() {
        return humanFactor;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Sex = new javax.swing.ButtonGroup();
        buttonGroup_experience = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton_Advanced = new javax.swing.JRadioButton();
        jRadioButton_Intermediate = new javax.swing.JRadioButton();
        jRadioButton_Beginner = new javax.swing.JRadioButton();
        jButton_Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Human Interference");

        jLabel2.setText("Age:");

        jLabel3.setText("Sex:");

        buttonGroup_Sex.add(jRadioButton_Male);
        jRadioButton_Male.setText("Male");

        buttonGroup_Sex.add(jRadioButton_Female);
        jRadioButton_Female.setText("Female");

        jLabel4.setText("Doctor's experience:");

        buttonGroup_experience.add(jRadioButton_Advanced);
        jRadioButton_Advanced.setText("Advanced ( > 8 years)");

        buttonGroup_experience.add(jRadioButton_Intermediate);
        jRadioButton_Intermediate.setText("Intermediate (3 - 8 years)");

        buttonGroup_experience.add(jRadioButton_Beginner);
        jRadioButton_Beginner.setText("Beginner (0 - 3 years)");

        jButton_Next.setText("Next -->");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_Female)
                            .addComponent(jRadioButton_Male)
                            .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_Intermediate)
                            .addComponent(jRadioButton_Beginner)
                            .addComponent(jRadioButton_Advanced))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Next)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton_Male))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Female)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton_Beginner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Intermediate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Advanced)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton_Next)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
        // Age of the patient
        double competence = getCompetence(jTextField_age.getText());
        
        // Get trust/experience of doctor
        double trust = getTrust();
        
        humanFactor = (competence + trust)/45;
        System.out.println("Human Interference 2: " + humanFactor);
        this.setVisible(false);
        eig = new EnvironmentalInfluenceGUI();
        eig.setVisible(true);
    }//GEN-LAST:event_jButton_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumanInterferenceGUI2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Sex;
    private javax.swing.ButtonGroup buttonGroup_experience;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton_Advanced;
    private javax.swing.JRadioButton jRadioButton_Beginner;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Intermediate;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JTextField jTextField_age;
    // End of variables declaration//GEN-END:variables

    private double getCompetence(String text) {
        int age = Integer.parseInt(text);
        if (age < 16 || age < 80) {
            return 6;
        }
        else if (age >= 16 && age <= 25) {
            return 12;
        }
        else if (age > 25 && age <= 40) {
            return 14;
        }
        else if (age > 40 && age <= 60) {
            return 10;
        }
        else {
            return 8;
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private double getTrust() {
        if (jRadioButton_Beginner.isSelected()){
            return 20;
        }
        else if (jRadioButton_Intermediate.isSelected()) {
            return 25;
        }
        else {
            return 28;
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
