/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package genericexpertsystem;

import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;

/**
 *
 * @author Peeral
 */
public class HumanInterferenceGUI extends javax.swing.JFrame {

    static private double reliability;
    HumanInterferenceGUI2 hig2;
    ArrayList<Double> factors;
    /**
     * Creates new form HumanInterferenceGUI
     */
    public HumanInterferenceGUI() {
        initComponents();
        hig2 = new HumanInterferenceGUI2();
    }

    public void setReliabity(double reliability) {
        HumanInterferenceGUI.reliability = reliability;
    }
    
    public double getReliability() {
        return reliability;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_sensorWorn = new javax.swing.ButtonGroup();
        buttonGroup_timesRemoved = new javax.swing.ButtonGroup();
        buttonGroup_timeToBeWorn = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_Yes = new javax.swing.JRadioButton();
        jRadioButton_No = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton_1_2 = new javax.swing.JRadioButton();
        jRadioButton_3_5 = new javax.swing.JRadioButton();
        jRadioButton_6_8 = new javax.swing.JRadioButton();
        jRadioButton_10 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton_24 = new javax.swing.JRadioButton();
        jRadioButton_24_48 = new javax.swing.JRadioButton();
        jRadioButton_48_72 = new javax.swing.JRadioButton();
        jRadioButton_72 = new javax.swing.JRadioButton();
        jButton_Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setText("Human Interference");

        jLabel2.setText("Was the sensor worn regularly?");

        buttonGroup_sensorWorn.add(jRadioButton_Yes);
        jRadioButton_Yes.setText("Yes");
        jRadioButton_Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_YesActionPerformed(evt);
            }
        });

        buttonGroup_sensorWorn.add(jRadioButton_No);
        jRadioButton_No.setText("No");

        jLabel3.setText("<html>If no, then give the number of times it was removed</html>");

        buttonGroup_timesRemoved.add(jRadioButton_1_2);
        jRadioButton_1_2.setText("1 - 2");

        buttonGroup_timesRemoved.add(jRadioButton_3_5);
        jRadioButton_3_5.setText("3 - 5");

        buttonGroup_timesRemoved.add(jRadioButton_6_8);
        jRadioButton_6_8.setText("6 - 8");

        buttonGroup_timesRemoved.add(jRadioButton_10);
        jRadioButton_10.setText("> 10");

        jLabel4.setText("<html>For how long was the sensor supposed to be worn?</html>");

        buttonGroup_timeToBeWorn.add(jRadioButton_24);
        jRadioButton_24.setText("< 24 hours");

        buttonGroup_timeToBeWorn.add(jRadioButton_24_48);
        jRadioButton_24_48.setText("24 - 48 hours");

        buttonGroup_timeToBeWorn.add(jRadioButton_48_72);
        jRadioButton_48_72.setText("48 - 72 hours");

        buttonGroup_timeToBeWorn.add(jRadioButton_72);
        jRadioButton_72.setText(" > 72 hours");

        jButton_Next.setText("Next -->");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_No)
                            .addComponent(jRadioButton_Yes)
                            .addComponent(jRadioButton_1_2)
                            .addComponent(jRadioButton_3_5)
                            .addComponent(jRadioButton_6_8)
                            .addComponent(jRadioButton_24)
                            .addComponent(jRadioButton_72)
                            .addComponent(jRadioButton_24_48)
                            .addComponent(jRadioButton_48_72)
                            .addComponent(jButton_Next)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton_10)
                        .addGap(42, 42, 42)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton_Yes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_1_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_3_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_6_8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_24_48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_48_72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton_Next)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_YesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_YesActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
        // Get the reliability factor in the human interference area
        reliability = getReliabilityFactor()/20;
        System.out.println("Human Interference 1: " + reliability);
        this.setVisible(false);
        hig2.setVisible(true);
    }//GEN-LAST:event_jButton_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HumanInterferenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumanInterferenceGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_sensorWorn;
    private javax.swing.ButtonGroup buttonGroup_timeToBeWorn;
    private javax.swing.ButtonGroup buttonGroup_timesRemoved;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton_10;
    private javax.swing.JRadioButton jRadioButton_1_2;
    private javax.swing.JRadioButton jRadioButton_24;
    private javax.swing.JRadioButton jRadioButton_24_48;
    private javax.swing.JRadioButton jRadioButton_3_5;
    private javax.swing.JRadioButton jRadioButton_48_72;
    private javax.swing.JRadioButton jRadioButton_6_8;
    private javax.swing.JRadioButton jRadioButton_72;
    private javax.swing.JRadioButton jRadioButton_No;
    private javax.swing.JRadioButton jRadioButton_Yes;
    // End of variables declaration//GEN-END:variables

    private double getReliabilityFactor() {
        if (jRadioButton_Yes.isSelected()) {
            return 20;
        }
        else if (jRadioButton_No.isSelected()) {
            for (Enumeration<AbstractButton> buttons = buttonGroup_timesRemoved.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    return getSensorRemovedConfidence(button.getText());
                }
            }
        }
        return 0;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private double getSensorRemovedConfidence(String text) {
        double timesRemovedConfidence = 0;
        
        if (text.equals("1 - 2")) {
            timesRemovedConfidence = 8;
        }
        else if (text.equals("3 - 5")) {
            timesRemovedConfidence = 6;
        }
        else if (text.equals("6 - 8")) {
            timesRemovedConfidence = 4;
        }
        else {
            timesRemovedConfidence = 2;
        }
        
        if (jRadioButton_24.isSelected()) {
            return 3 + timesRemovedConfidence;
        }
        else if (jRadioButton_24_48.isSelected()) {
            return 6 + timesRemovedConfidence;
        }
        else if (jRadioButton_48_72.isSelected()) {
            return 7.5 + timesRemovedConfidence;
        }
        else {
            return 9.5 + timesRemovedConfidence;
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
